---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation
notifications:
  slack:
    on_failure: always


fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:


 # =============================================windows=============================================

    - name: "kubectl minikube Python 3.8 on Windows"
      os: windows
      language: shell
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.1
        - pip install virtualenv
        - virtualenv $HOME/venv
        - source $HOME/venv/Scripts/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      script:
        - choco install kubernetes-cli
        - choco install minikube
        # - minikube start --driver=none # The driver 'none' is not supported on windows
        # - minikube status
        - kubectl version --client
        # - set USERPROFILE #query the value of %USERPROFILE%
        # - set #see all currently defined environment variables    #USERPROFILE='C:\Users\travis'
        - echo cd %USERPROFILE% #when debugging a command
        - echo %cd% #print current path
        - echo mkdir %USERPROFILE%\.kube
        - mkdir %USERPROFILE%\.kube
        - echo cd %USERPROFILE%\.kube
        - cd %USERPROFILE%\.kube
        # - mkdir .kube
        # - cd .kube
        - cd #print current path
        # - New-Item config -type file #Configure kubectl to use a remote Kubernetes cluster:
      after_success:
        - deactivate
