---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation
notifications:
  slack:
    on_failure: always


fleet_script_tasks : &fleet_script_tasks
      script:
        - python --version
fleet_install_tasks : &fleet_install_tasks
      install:
        - pip install -r requirements.txt


matrix:
  fast_finish: true
  include:


    #https://minikube.sigs.k8s.io/docs/drivers/
    #https://minikube.sigs.k8s.io/docs/drivers/podman/
    #https://kubernetes.io/docs/setup/learning-environment/minikube/
    #https://kubernetes.io/docs/tasks/tools/install-minikube/
    #https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
    - name: "minikube containerd as the container runtime,  Python 3.7 on bionic amd64"
      dist: bionic
      addons:
           snaps:
             - name: minikube
               confinement: strict
               channel: stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      # <<: *fleet_script_minikube_latest_tasks
      script:
        - | #To check if virtualization is supported on Linux, run the following command and verify that the output is non-empty:
            set -eo pipefail #safety for script
            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
                     echo "virtualization is not supported"
            else
                  echo "===================================="
                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
                  echo "===================================="
                  echo "virtualization is supported"
            fi
        - |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
          chmod +x ./kubectl && \
          sudo mv ./kubectl /usr/local/bin/kubectl &&
          kubectl version --client
        - | #Install Minikube via direct download,add the Minikube executable to the path
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
          chmod +x minikube && \
          sudo mkdir -p /usr/local/bin/ && \
          sudo install minikube /usr/local/bin/
        # # Install podman
        # - . /etc/os-release
        # - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        # - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        # - sudo apt-get update -qq
        # - sudo apt-get -qqy install podman slirp4netns #https://github.com/rootless-containers/slirp4netns
        # - podman info #his command displays the information related to the host such as the Kernel version, swap space used
        # - "podman build ."
        # - podman images #lists all the images
        # - sudo podman run  -p 80:80 -dit centos
        # - podman ps -a
        # - podman stop eed30719cd37
        # - podman rm eed30719cd37
        # - podman rmi 785188cd988c
        # - podman pod list #The pod create command creates a pod with an infra container by default associated with it unless explicitly set with infra flag as false.
        # - podman pod create --infra = false #Error: `podman pod create` takes no arguments
        # - podman pod list
        # - snap info --verbose minikube
        - minikube version #minikube version: v1.11.0
        # - minikube config set driver podman #unknown command "config" for "minikube"
        - docker pull gcr.io/k8s-minikube/kicbase:v0.0.10
        # - sudo podman network ls
        # - podman info | grep rootless
        #https://github.com/kubernetes/minikube/issues/7480
        #https://github.com/kubernetes/minikube/issues/8124
        # - | #Starting a cluster on alternative container runtimes, with containerd
        #   minikube start \
        #   --network-plugin=cni \
        #   --enable-default-cni \
        #   --container-runtime=containerd \
        #   --bootstrapper=kubeadm
        # - minikube start --driver=podman --container-runtime=cri-o #Start a cluster using the podman driver
        - | #Starting a cluster on alternative container runtimes,use the extended version with containerd
          minikube start \
          --network-plugin=cni \
          --enable-default-cni \
          --extra-config=kubelet.container-runtime=remote \
          --extra-config=kubelet.container-runtime-endpoint=unix:///run/containerd/containerd.sock \
          --extra-config=kubelet.image-service-endpoint=unix:///run/containerd/containerd.sock \
          --bootstrapper=kubeadm
        - echo "============================Waiting for Kubernetes to be ready========================================"
        - |
          echo "Waiting for Kubernetes to be ready ..."
          for i in {1..150}; do # Timeout after 2 minutes, 150x2=300 secs
            if kubectl get pods --namespace=kube-system |grep Running ; then
              break
            fi
            sleep 2
          done
        - echo "======================================================================================================="
        - echo "============================smoke tests=============================================================="
        - kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10 #create a Kubernetes Deployment using an existing image named echoserver, which is a simple HTTP server and expose it on port 8080 using --port.
        - kubectl expose deployment hello-minikube --type=NodePort --port=8080 #To access the hello-minikube Deployment, expose it as a Service,The option --type=NodePort specifies the type of the Service
        - kubectl get pod #Check if the Pod is up and running
        - minikube service hello-minikube --url #Get the URL of the exposed Service to view the Service details
        - kubectl delete services hello-minikube #Delete the hello-minikube Service
        - kubectl delete deployment hello-minikube #Delete the hello-minikube Deployment
        - echo "============================smoke tests=============================================================="
        - minikube stop #Stop the local Minikube cluster
        - minikube delete #Delete the local Minikube cluster

      after_success:
        - deactivate

    #Podman - container (experimental)
    #https://minikube.sigs.k8s.io/docs/drivers/
    #https://minikube.sigs.k8s.io/docs/drivers/podman/
    # https://kubernetes.io/docs/setup/learning-environment/minikube/
    #https://kubernetes.io/docs/tasks/tools/install-minikube/
    #https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-on-linux
    - name: "minikube CRI-O as the container runtime,  Python 3.7 on bionic amd64"
      dist: bionic
      addons:
           snaps:
             - name: minikube
               confinement: strict
               channel: stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      # <<: *fleet_script_minikube_latest_tasks
      script:
        - | #To check if virtualization is supported on Linux, run the following command and verify that the output is non-empty:
            set -eo pipefail #safety for script
            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
                     echo "virtualization is not supported"
            else
                  echo "===================================="
                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
                  echo "===================================="
                  echo "virtualization is supported"
            fi
        - |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
          chmod +x ./kubectl && \
          sudo mv ./kubectl /usr/local/bin/kubectl &&
          kubectl version --client
        - | #Install Minikube via direct download,add the Minikube executable to the path
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
          chmod +x minikube && \
          sudo mkdir -p /usr/local/bin/ && \
          sudo install minikube /usr/local/bin/
        # # Install podman
        # - . /etc/os-release
        # - sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
        # - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
        # - sudo apt-get update -qq
        # - sudo apt-get -qqy install podman slirp4netns #https://github.com/rootless-containers/slirp4netns
        # - podman info #his command displays the information related to the host such as the Kernel version, swap space used
        # - "podman build ."
        # - podman images #lists all the images
        # - sudo podman run  -p 80:80 -dit centos
        # - podman ps -a
        # - podman stop eed30719cd37
        # - podman rm eed30719cd37
        # - podman rmi 785188cd988c
        # - podman pod list #The pod create command creates a pod with an infra container by default associated with it unless explicitly set with infra flag as false.
        # - podman pod create --infra = false #Error: `podman pod create` takes no arguments
        # - podman pod list
        # - snap info --verbose minikube
        - minikube version #minikube version: v1.11.0
        # - minikube config set driver podman #unknown command "config" for "minikube"
        # - sudo podman network ls
        # - sudo minikube start \
        #     --network-plugin=cni \
        #     --enable-default-cni \
        #     --container-runtime=cri-o \
        #     --bootstrapper=kubeadm
        #use the extended version
        - docker pull gcr.io/k8s-minikube/kicbase:v0.0.10
        - minikube start \
                --network-plugin=cni \
                --enable-default-cni \
                --extra-config=kubelet.container-runtime=remote \
                --extra-config=kubelet.container-runtime-endpoint=/var/run/crio.sock \
                --extra-config=kubelet.image-service-endpoint=/var/run/crio.sock \
                --bootstrapper=kubeadm
        # - |
        #   sudo minikube start \
        #   --network-plugin=cni \
        #   --enable-default-cni \
        #   --extra-config=kubelet.container-runtime=remote \
        #   --extra-config=kubelet.container-runtime-endpoint=/var/run/crio.sock \
        #   --extra-config=kubelet.image-service-endpoint=/var/run/crio.sock \
        #   --driver=podman
        # - minikube start --driver=podman --container-runtime=cri-o #Start a cluster using the podman driver
        - echo "============================Waiting for Kubernetes to be ready========================================"
        - |
          echo "Waiting for Kubernetes to be ready ..."
          for i in {1..150}; do # Timeout after 2 minutes, 150x2=300 secs
            if kubectl get pods --namespace=kube-system |grep Running ; then
              break
            fi
            sleep 2
          done
        - echo "======================================================================================================="
        - echo "============================smoke tests=============================================================="
        - kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10 #create a Kubernetes Deployment using an existing image named echoserver, which is a simple HTTP server and expose it on port 8080 using --port.
        - kubectl expose deployment hello-minikube --type=NodePort --port=8080 #To access the hello-minikube Deployment, expose it as a Service,The option --type=NodePort specifies the type of the Service
        - kubectl get pod #Check if the Pod is up and running
        - minikube service hello-minikube --url #Get the URL of the exposed Service to view the Service details
        - kubectl delete services hello-minikube #Delete the hello-minikube Service
        - kubectl delete deployment hello-minikube #Delete the hello-minikube Deployment
        - echo "============================smoke tests=============================================================="
        - minikube stop #Stop the local Minikube cluster
        - minikube delete #Delete the local Minikube cluster

      after_success:
        - deactivate

    - name: "minikube docker as the container runtime,  Python 3.7 on bionic amd64"
      dist: bionic
      addons:
           snaps:
             - name: minikube
               confinement: strict
               channel: stable
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      <<: *fleet_install_tasks
      <<: *fleet_script_tasks
      # <<: *fleet_script_minikube_latest_tasks
      script:
        - | #To check if virtualization is supported on Linux, run the following command and verify that the output is non-empty:
            set -eo pipefail #safety for script
            if [[ $(egrep -c '(vmx|svm)' /proc/cpuinfo) == 0 ]]; then #check if virtualization is supported on Linux, xenial fails w 0, bionic works w 2
                     echo "virtualization is not supported"
            else
                  echo "===================================="
                  echo eval "$(egrep -c '(vmx|svm)' /proc/cpuinfo)" 2>/dev/null
                  echo "===================================="
                  echo "virtualization is supported"
            fi
        - |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
          chmod +x ./kubectl && \
          sudo mv ./kubectl /usr/local/bin/kubectl &&
          kubectl version --client
        - docker pull gcr.io/k8s-minikube/kicbase:v0.0.10
        - | #Install Minikube via direct download,add the Minikube executable to the path
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
          chmod +x minikube && \
          sudo mkdir -p /usr/local/bin/ && \
          sudo install minikube /usr/local/bin/
        - minikube version #minikube version: v1.11.0
        - minikube start --driver=docker #No hypervisor required when run on Linux
        - echo "============================Waiting for Kubernetes to be ready========================================"
        - |
          echo "Waiting for Kubernetes to be ready ..."
          for i in {1..150}; do # Timeout after 2 minutes, 150x2=300 secs
            if kubectl get pods --namespace=kube-system |grep Running ; then
              break
            fi
            sleep 2
          done
        - echo "======================================================================================================="
        - echo "============================smoke tests=============================================================="
        - kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10 #create a Kubernetes Deployment using an existing image named echoserver, which is a simple HTTP server and expose it on port 8080 using --port.
        - kubectl expose deployment hello-minikube --type=NodePort --port=8080 #To access the hello-minikube Deployment, expose it as a Service,The option --type=NodePort specifies the type of the Service
        - kubectl get pod #Check if the Pod is up and running
        - minikube service hello-minikube --url #Get the URL of the exposed Service to view the Service details
        - kubectl delete services hello-minikube #Delete the hello-minikube Service
        - kubectl delete deployment hello-minikube #Delete the hello-minikube Deployment
        - echo "============================smoke tests=============================================================="
        - minikube stop #Stop the local Minikube cluster
        - minikube delete #Delete the local Minikube cluster
