---
sudo: required
dist: bionic
env:
  global:
  # auto vagrant installation
notifications:
  slack:
    on_failure: always


matrix:
  fast_finish: true
  include:

    - name: "deploy minikube kubectl w homebrew on macOS 10.15.4 osx xcode11.5"
      os: osx
      osx_image: xcode11.5
      language: shell
      addons:
        homebrew:
          packages:
            - kubectl #kubernetes-cli 1.18.3
            - minikube #minikube 1.11.0
          casks: # Installing Casks
            - podman
          update: true
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        - kubectl version --client
        - minikube version
        - brew cat kubectl
        - brew cat minikube
        - brew home kubectl
        - brew home minikube
        - brew info kubectl
        - brew info minikube
        # - brew doctor #Check system for potential problems
        - brew update #Update brew and cask
        - brew cask upgrade
        - brew cask info podman
      after_success:
        - brew uninstall kubectl minikube
        - brew cleanup kubectl minikube
        - brew cask uninstall --force podman
        - deactivate

# https://github.com/containers/podman
# https://podman.io/getting-started/installation
    - name: "deploy podman Python 2.7.17 on macOS 10.15.4 osx xcode11.5"
      os: osx
      osx_image: xcode11.5
      language: shell
      addons:
        homebrew:
          packages:
            - podman 
          update: true
      before_install:
        - pip install virtualenv
        - virtualenv -p $(which python2) ~venvpy2
        - source ~venvpy2/bin/activate
        - python --version
        - pip install -r requirements.txt
      script:
        - brew info podman
        # - brew doctor #Check system for potential problems
        - brew update #Update brew and cask
        - brew cask upgrade
        - brew cask info podman
      after_success:
        - brew uninstall podman 
        - brew podman
        - deactivate